name: Merge Request Merged
on:
  pull_request:
    types:
      - closed
jobs:
  build_npm_packages:
    name: Publish tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - run: git config --global user.email "x64vs32x@mail.ru"
      - run: git config --global user.name "Sergei Nagaitsev"
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: yarn install --frozen-lockfile
      - run: yarn nx affected --target=build --configuration=production --base=origin/main~1
      - run: yarn nx affected --target=version --base=origin/main~1 --push --parallel=1 --trackDeps
