name: Merge Request
on:
  pull_request:
# For the develop branch only.
#    branches:
#      - master
jobs:
  build_npm_packages:
    name: Build NPM package and then publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: git log --pretty=%B HEAD...origin/main
      - run: yarn install --frozen-lockfile
#      - run: yarn nx affected --target=build --configuration=production --base=origin/main
      - run: yarn nx affected --target=version --base=last-release --head=HEAD --trackDeps --preset=angular --dryRun
#      - name: Log in to Docker Hub
#        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
#        with:
#          images: x64vs32x/my-words
#      - name: Build and push Docker image
#        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
