name: Merge Request Merged
on:
  push:
    branches:
      - main
jobs:
  build_npm_packages:
    name: Build NPM package and then publish docker image
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: git fetch origin main:refs/remotes/origin/main
      - run: yarn nx affected --target=version --base=origin/main
